import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { promises as fs } from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import {
  WATCHDOG_STANDALONE_BODY,
} from '../src/watchdog.standalone.js'
import { pluginVersion } from '../src/watchdog.js'

describe('watchdog standalone body', () => {
  it('starts with a use-strict directive', () => {
    expect(WATCHDOG_STANDALONE_BODY.trimStart().startsWith("'use strict'")).toBe(true)
  })

  it('does not require any external modules', () => {
    // No `require('npm-package')` or `import 'npm-package'`.
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(/require\(['"]@/)
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(/from\s+['"]@/)
    // Only Node built-ins should appear as `require('node:...')` or `require('fs')` etc.
    const requires = [...WATCHDOG_STANDALONE_BODY.matchAll(/require\(['"]([^'"]+)['"]\)/g)].map((m) => m[1])
    for (const r of requires) {
      const builtin = ['fs', 'path', 'os', 'http', 'net', 'child_process', 'crypto', 'node:fs', 'node:path', 'node:os', 'node:http', 'node:net', 'node:child_process', 'node:crypto']
      expect(builtin).toContain(r)
    }
  })

  it('contains the required state-machine primitives', () => {
    for (const sym of [
      'function probe',
      'function triage',
      'function killWeb',
      'function startWeb',
      'function activateSafeMode',
      'function clearSafeMode',
      'function stageDisableRow',
      'function loadConfig',
      'singleInstance',
      'recoveryBudgetMs',
      'healthFailuresToRecover',
    ]) {
      expect(WATCHDOG_STANDALONE_BODY).toContain(sym)
    }
  })

  it('does not call pkill or killall', () => {
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(/pkill|killall/)
  })

  it('does not unref the main-loop tick timer (regression: v0.2.4 self-exit)', () => {
    // Regression for the v0.2.4 self-exit bug. `.unref()` on the tick
    // setTimeout left the event loop with no ref'd handle during the
    // 30 s gap between probes, so Node exited cleanly and launchd's
    // KeepAlive re-spawned the watchdog in a tight loop.
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(
      /setTimeout\(loop,\s*CFG\.healthIntervalMs\)\.unref\(\)/,
    )
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(
      /setTimeout\(loop,\s*5000\)\.unref\(\)/,
    )
  })

  it('schedules the next tick via finally (regression: v0.2.6 loop death)', () => {
    // Regression for the v0.2.6 loop-death bug observed live on macOS:
    // tick().catch(...).then(setTimeout) silently stopped scheduling new
    // ticks when tick() returned a never-resolving promise (5 minutes of
    // 0% CPU on PID 71994). The fix wraps setTimeout in `.finally` so
    // the next tick is scheduled even when tick() throws synchronously
    // or returns a hanging promise. We use [\s\S] to match across the
    // multi-line arrow body.
    expect(WATCHDOG_STANDALONE_BODY).toMatch(/\.finally\(\s*\(\)\s*=>\s*setTimeout\(run/)
  })

  it('emits a heartbeat line every N ticks when healthy', () => {
    // Without the heartbeat, a healthy watchdog is invisible in the log
    // (it only writes on failure / recovery). The heartbeat makes the
    // operator's "is the watchdog still alive?" question trivial.
    expect(WATCHDOG_STANDALONE_BODY).toMatch(/heartbeat/)
    expect(WATCHDOG_STANDALONE_BODY).toMatch(/HEARTBEAT_EVERY_N_TICKS/)
  })

  it('still unrefs the spawned dsh web child process', () => {
    // The spawned dsh web subprocess should be detached from the
    // watchdog's event loop via `child.unref()`. This is the one
    // `.unref()` call that must stay.
    expect(WATCHDOG_STANDALONE_BODY).toMatch(/child\.unref\(\)/)
  })

  it('exposes a plugin version stamp at runtime', () => {
    // The version helper is sourced from the *plugin* package.json; the body
    // itself is a string and the stamp is injected by `buildWatchdogScript()`.
    expect(pluginVersion()).toMatch(/^\d+\.\d+\.\d+/)
  })
})

describe('generated script', () => {
  let tmpHome: string

  beforeEach(async () => {
    tmpHome = await fs.mkdtemp(path.join(os.tmpdir(), 'dsh-doctor-test-'))
    process.env.DSH_HOME = tmpHome
  })
  afterEach(async () => {
    delete process.env.DSH_HOME
    await fs.rm(tmpHome, { recursive: true, force: true })
  })

  it('installWatchdogScript writes a parseable, self-contained JS file', async () => {
    const { installWatchdogScript } = await import('../src/watchdog.js')
    const p = await installWatchdogScript()
    expect(p).toBeTruthy()
    const text = await fs.readFile(p, 'utf8')
    // The header is in the actual file, the body follows.
    expect(text).toMatch(/auto-generated by @d86e\/dsh-doctor v\d+\.\d+\.\d+/)
    expect(text).toContain("'use strict'")
    // Smoke: parse it with `new Function` to ensure no syntax error. This
    // does not execute the body, so it's safe to run in tests.
    // eslint-disable-next-line no-new-func
    expect(() => new Function(text)).not.toThrow()
  })
})
