import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { promises as fs } from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import {
  WATCHDOG_STANDALONE_BODY,
} from '../src/watchdog.standalone.js'
import { pluginVersion } from '../src/watchdog.js'

describe('watchdog standalone body', () => {
  it('starts with a use-strict directive', () => {
    expect(WATCHDOG_STANDALONE_BODY.trimStart().startsWith("'use strict'")).toBe(true)
  })

  it('does not require any external modules', () => {
    // No `require('npm-package')` or `import 'npm-package'`.
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(/require\(['"]@/)
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(/from\s+['"]@/)
    // Only Node built-ins should appear as `require('node:...')` or `require('fs')` etc.
    const requires = [...WATCHDOG_STANDALONE_BODY.matchAll(/require\(['"]([^'"]+)['"]\)/g)].map((m) => m[1])
    for (const r of requires) {
      const builtin = ['fs', 'path', 'os', 'http', 'child_process', 'crypto', 'node:fs', 'node:path', 'node:os', 'node:http', 'node:child_process', 'node:crypto']
      expect(builtin).toContain(r)
    }
  })

  it('contains the required state-machine primitives', () => {
    for (const sym of [
      'function probe',
      'function triage',
      'function killWeb',
      'function startWeb',
      'function activateSafeMode',
      'function clearSafeMode',
      'function stageDisableRow',
      'function loadConfig',
      'singleInstance',
      'recoveryBudgetMs',
      'healthFailuresToRecover',
    ]) {
      expect(WATCHDOG_STANDALONE_BODY).toContain(sym)
    }
  })

  it('does not call pkill or killall', () => {
    expect(WATCHDOG_STANDALONE_BODY).not.toMatch(/pkill|killall/)
  })

  it('exposes a plugin version stamp at runtime', () => {
    // The version helper is sourced from the *plugin* package.json; the body
    // itself is a string and the stamp is injected by `buildWatchdogScript()`.
    expect(pluginVersion()).toMatch(/^\d+\.\d+\.\d+/)
  })
})

describe('generated script', () => {
  let tmpHome: string

  beforeEach(async () => {
    tmpHome = await fs.mkdtemp(path.join(os.tmpdir(), 'dsh-doctor-test-'))
    process.env.DSH_HOME = tmpHome
  })
  afterEach(async () => {
    delete process.env.DSH_HOME
    await fs.rm(tmpHome, { recursive: true, force: true })
  })

  it('installWatchdogScript writes a parseable, self-contained JS file', async () => {
    const { installWatchdogScript } = await import('../src/watchdog.js')
    const p = await installWatchdogScript()
    expect(p).toBeTruthy()
    const text = await fs.readFile(p, 'utf8')
    // The header is in the actual file, the body follows.
    expect(text).toMatch(/auto-generated by @d86e\/dsh-doctor v\d+\.\d+\.\d+/)
    expect(text).toContain("'use strict'")
    // Smoke: parse it with `new Function` to ensure no syntax error. This
    // does not execute the body, so it's safe to run in tests.
    // eslint-disable-next-line no-new-func
    expect(() => new Function(text)).not.toThrow()
  })
})
