/**
 * Watchdog generator. Reads the standalone body, prepends a header with
 * the plugin's version stamp, and writes it to `$DSH_HOME/doctor/watchdog.js`.
 *
 * The generated script is also packaged into `lib/watchdog.standalone.body`
 * for tests that want to validate the *current* body without going through
 * the install path.
 *
 * @module dsh-doctor/watchdog
 */

import { promises as fs } from 'node:fs'
import { StatePaths, ensureDir, writeFileAtomic, readFileOrNull } from './state.js'
import { WATCHDOG_STANDALONE_BODY } from './watchdog.standalone.js'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const PLUGIN_VERSION: string = (() => {
  try {
    const pkg = require('../package.json') as { version?: string }
    return pkg.version ?? '0.0.0'
  } catch {
    return '0.0.0'
  }
})()

const HEADER = `'use strict'
/* eslint-disable */
/**
 * dsh-doctor watchdog — auto-generated by @d86e/dsh-doctor v${PLUGIN_VERSION}
 * Do not edit by hand. Edit src/watchdog.standalone.ts and run
 * dsh_doctor_reinstall. Generated at ${new Date().toISOString()}.
 */
`

/** Build the full script body (header + body). */
export function buildWatchdogScript(): string {
  return HEADER + '\n' + WATCHDOG_STANDALONE_BODY + '\n'
}

/** Write the watchdog script to its target path. Returns the path. */
export async function installWatchdogScript(): Promise<string> {
  await ensureDir(StatePaths.logsDir())
  const p = StatePaths.watchdogScript()
  await writeFileAtomic(p, buildWatchdogScript())
  // Also write the source-of-truth body for tests.
  await writeFileAtomic(
    `${StatePaths.doctorHome()}/watchdog.standalone.body.txt`,
    WATCHDOG_STANDALONE_BODY,
  )
  return p
}

/** Read the current watchdog script (or `null` if not installed). */
export async function readWatchdogScript(): Promise<string | null> {
  return readFileOrNull(StatePaths.watchdogScript())
}

/** Is the watchdog currently installed (script + marker present)? */
export async function isWatchdogInstalled(): Promise<boolean> {
  const [script, marker] = await Promise.all([
    readFileOrNull(StatePaths.watchdogScript()),
    readFileOrNull(StatePaths.installedMarker()),
  ])
  return script !== null && marker !== null
}

/** Get the plugin version stamped into the header. */
export function pluginVersion(): string {
  return PLUGIN_VERSION
}

/** Read the body of the standalone script (for tests). */
export async function readStandaloneBodyFromDisk(): Promise<string | null> {
  return readFileOrNull(`${StatePaths.doctorHome()}/watchdog.standalone.body.txt`)
}

/** Helper used by tests to delete the watchdog files without going through uninstall. */
export async function _testRemoveWatchdogFiles(): Promise<void> {
  for (const f of [
    StatePaths.watchdogScript(),
    `${StatePaths.doctorHome()}/watchdog.standalone.body.txt`,
    StatePaths.installedMarker(),
    StatePaths.stoppedMarker(),
  ]) {
    try {
      await fs.unlink(f)
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
    }
  }
}
