// @ts-nocheck — the WATCHDOG_STANDALONE_BODY string below is raw
// JavaScript that we hand to `new Function()` at install time. TypeScript
// would otherwise parse every character and reject arrow functions with
// return-type annotations like `() => void` that are perfectly valid JS.
// Keep this file pure-JS-shaped (no TS-only syntax inside the template).
/* eslint-disable */
/**
 * Source-of-truth body for the standalone watchdog script.
 *
 * This module exports a string of valid JavaScript that:
 *   - depends only on Node built-ins (no `node_modules` access),
 *   - runs as the main module of a fresh `node` invocation,
 *   - implements the full state machine in docs/ARCHITECTURE.md.
 *
 * The plugin reads this string, prepends a header (version stamp + safety
 * disclaimer), and writes it to `$DSH_HOME/doctor/watchdog.js` at install
 * time. Upgrading the plugin regenerates the script — the *next* watchdog
 * tick picks up the new body. No re-spawn dance.
 *
 * @module dsh-doctor/watchdog.standalone
 */

// We use the String.raw tagged template (the `@ts-nocheck` at the top
// of this file is what silences the TS parse, not the tag itself).
// CRITICAL: a raw template does NOT escape-cook its contents, so every
// backslash in the body below is passed through to the generated script
// verbatim. That is why the regexes here are written with single
// backslashes (\s \d \. ) and the join/split string literals for
// newlines are written as '\n' — exactly what the generated script
// needs to see. A plain `String\`...\`` tag (the pre-v0.2.22 state)
// cooked \s to s and \d to d, silently breaking the triage regexes.
export const WATCHDOG_STANDALONE_BODY: string = String.raw`'use strict'
/**
 * dsh-doctor watchdog — standalone, dependency-free, runs as a per-user
 * platform service. This file is generated by the @d86e/dsh-doctor plugin
 * at install time and regenerated on upgrade. Do not edit by hand; edit
 * src/watchdog.standalone.ts and run dsh_doctor_reinstall.
 *
 * The script is intentionally simple: a single async loop, one health
 * probe per tick, three possible recovery paths (simple / complex / alarm).
 * The 60-second recovery budget is enforced by a monotonic timer.
 */

const fs   = require('node:fs')
const path = require('node:path')
const os   = require('node:os')
const net  = require('node:net')
const http = require('node:http')
const cp   = require('node:child_process')
const crypto = require('node:crypto')

// ---------- paths & config ----------------------------------------------------

const DSH_HOME   = process.env.DSH_HOME   || path.join(os.homedir(), '.dsh')
const WEB_PORT   = Number(process.env.DSH_WEB_PORT) || 3080
const DOCTOR_DIR = path.join(DSH_HOME, 'doctor')
const CONFIG_F   = path.join(DOCTOR_DIR, 'config.json')
const LOG_F      = path.join(DOCTOR_DIR, 'logs', 'watchdog.log')
const LKG_F      = path.join(DOCTOR_DIR, 'last-known-good.json')
const INSTALLED  = path.join(DOCTOR_DIR, '.doctor-installed')
const STOPPED    = path.join(DOCTOR_DIR, '.doctor-stopped')
const LOCK       = path.join(DOCTOR_DIR, '.doctor-restart.lock')
const PID_F      = path.join(DOCTOR_DIR, '.doctor-watchdog.pid')
const LAST_TICK  = path.join(DOCTOR_DIR, '.doctor-last-tick')
const STARTED    = path.join(DOCTOR_DIR, '.doctor-started')
const SAFE_MODE  = path.join(DOCTOR_DIR, 'safe-mode.patch.yml')
const PROFILE_DIR= path.join(DSH_HOME, 'profiles', 'web')
const PATCH_F    = path.join(PROFILE_DIR, 'cordis.patch.yml')
const WEB_PID    = path.join(PROFILE_DIR, '.dsh-web.pid')
const LOG_MAX    = 5 * 1024 * 1024
const LOG_BACKUPS= 3

let CFG = {
  // NOTE: these four values must equal Defaults in src/config.ts — the
  // plugin always writes the fully-resolved config (defaults included)
  // to config.json on install, so the literal the daemon sees in
  // production is the plugin's. The values here only matter for a
  // config.json that never landed; a drift-guard test pins them.
  healthIntervalMs: 2000,
  healthFailuresToRecover: 3,
  recoveryBudgetMs: 60000,
  safeModeBundles: ['dsh-core'],
  triageLogLines: 1000,
}

// ---------- logging (rotation) ------------------------------------------------

function log(level, msg) {
  const ts = new Date().toISOString()
  const line = '[' + ts + '] [' + level + '] ' + msg + '\n'
  try { fs.mkdirSync(path.dirname(LOG_F), { recursive: true }) } catch (_) {}
  try { fs.appendFileSync(LOG_F, line) } catch (_) {}
  try {
    const st = fs.statSync(LOG_F)
    if (st.size >= LOG_MAX) rotate()
  } catch (_) {}
}

function rotate() {
  for (let i = LOG_BACKUPS; i >= 1; i--) {
    const src = i === 1 ? LOG_F : (LOG_F + '.' + (i - 1))
    const dst = LOG_F + '.' + i
    try { fs.renameSync(src, dst) } catch (_) {}
  }
}

// ---------- config load -------------------------------------------------------

function loadConfig() {
  try {
    const txt = fs.readFileSync(CONFIG_F, 'utf8')
    const parsed = JSON.parse(txt)
    if (parsed && typeof parsed === 'object') Object.assign(CFG, parsed)
  } catch (_) {}
  // env overrides
  const n = (k, fb) => {
    const v = process.env[k]
    if (v === undefined || v === '') return fb
    const x = Number(v); return Number.isFinite(x) && x > 0 ? x : fb
  }
  CFG.healthIntervalMs        = n('DSH_DOCTOR_HEALTH_INTERVAL', CFG.healthIntervalMs)
  CFG.healthFailuresToRecover = n('DSH_DOCTOR_HEALTH_FAILURES', CFG.healthFailuresToRecover)
  CFG.recoveryBudgetMs        = n('DSH_DOCTOR_BUDGET_MS', CFG.recoveryBudgetMs)
  CFG.triageLogLines          = n('DSH_DOCTOR_TRIAGE_LOG_LINES', CFG.triageLogLines)
}

// ---------- triage (inlined, dep-free) ---------------------------------------

const PATTERNS = [
  { id: 'eaddrinuse',             pri: 100, re: /EADDRINUSE.*?(?:127\.0\.0\.1|0\.0\.0\.0|::):(\d+)/,           act: () => ({ kind: 'kill-pid-and-restart' }) },
  { id: 'duplicate-loader-entry', pri: 90,  re: /duplicate loader entry id:\s*([A-Za-z0-9_.\-@/]+)/,             act: (m) => ({ kind: 'disable-row', id: m[1] }) },
  { id: 'schema-parse-error',     pri: 80,  re: /Schema (?:parse|validation) error[^\n]*?(?:@([A-Za-z0-9_.\-]+)\/([A-Za-z0-9_.\-]+)|^([A-Za-z][A-Za-z0-9_.\-]{1,})$)/m, act: (m) => ({ kind: 'disable-row', id: (m[1] && m[2]) ? '@' + m[1] + '/' + m[2] : (m[3] || 'unknown') }) },
  { id: 'cannot-find-module',     pri: 70,  re: /Cannot find module ['"]([^'"]+)['"]/,                          act: (m) => ({ kind: 'disable-row', id: guessPkg(m[1]) }) },
  { id: 'plugin-load-error',      pri: 60,  re: /(?:Failed to (?:load|apply)|Error (?:loading|applying)) plugin ['"]?([@A-Za-z0-9_.\-/]+)['"]?/, act: (m) => ({ kind: 'disable-row', id: m[1] }) },
  { id: 'node-version-mismatch',  pri: 95,  re: /Requires Node(?:\.js)?\s+[\`'"]?([~^]?\d[\d.]*)/i,            act: (m) => ({ kind: 'notify-user', reason: 'plugin requires Node ' + (m && m[1] || '?') + ' but dsh ships an older Node.' }) },
  { id: 'disk-full',              pri: 90,  re: /ENOSPC.*?(?:no space left|disk full)/i,                          act: () => ({ kind: 'notify-user', reason: 'disk full (ENOSPC). Free space under ~/.dsh/doctor/logs.' }) },
  { id: 'corrupt-patch-yaml',     pri: 88,  re: /(?:patch|yaml|YAML).*?(?:parse|syntax)\s*error|cordis\.patch\.yml.*?invalid/i, act: () => ({ kind: 'cleanup-and-restart', reason: 'corrupt cordis.patch.yml' }) },
  { id: 'cordis-schema-validate', pri: 85,  re: /Cannot read propert(?:y|ies) of undefined \(reading ['"]validate['"]\)|Config\["~standard"\]/, act: () => ({ kind: 'safe-mode', reason: 'cordis 4.x Config[~standard].validate missing' }) },
  { id: 'pnpm-peer-conflict',     pri: 78,  re: /(?:peer\s+dep(?:endency|endencies)?|ERESOLVE)[^\n]*?(@?[A-Za-z0-9_.\-]+(?:\/[A-Za-z0-9_.\-]+)?)@[\^~]?[\d.]+[^\n]*?(?:incompatible|conflict)/i, act: (m) => ({ kind: 'disable-row', id: guessPkg(m && m[1]) }) },
  { id: 'plugin-export-missing',  pri: 75,  re: /(?:Plugin|module|Bundle)\s+['"]?([@A-Za-z0-9_.\-\/]+)?['"]?\s+(?:did not|must|should) export(?:\s+(?:a\s+)?['"]name['"]\s+and\s+['"]apply['"]|\s+['"]name['"]\s+and\s+['"]apply['"]|\s+name\s+and\s+apply)/, act: (m) => ({ kind: 'disable-row', id: (m && m[1]) || 'unknown' }) },
  { id: 'plugin-file-missing',    pri: 72,  re: /ENOENT.*?['"]([^'"]+\.(?:js|mjs|cjs|ts))['"]|Cannot find (?:module|file) ['"]([^'"]+\.(?:js|mjs|cjs|ts))['"]/, act: (m) => ({ kind: 'disable-row', id: guessPkgFromPath(m && (m[1] || m[2])) }) },
]

function guessPkg(spec) {
  if (!spec) return 'unknown'
  const s = String(spec).replace(/^node:/, '')
  const parts = s.split('/')
  if (s.startsWith('@') && parts.length >= 2) return parts[0] + '/' + parts[1]
  return parts[0]
}

/**
 * Guess a package id from a file path. The plugin-file-missing pattern
 * captures absolute-ish paths like
 *   /Users/x/.dsh/node_modules/@scope/dsh-missing/lib/index.js
 * and we want the segment after the last node_modules: @scope/dsh-missing.
 * Until v0.2.22 this function was referenced by the pattern table but
 * never defined — every plugin-file-missing triage threw a
 * ReferenceError inside the standalone watchdog.
 */
function guessPkgFromPath(p) {
  if (!p) return 'unknown'
  const s = String(p)
  const nm = s.match(/node_modules[\/](?:@([^\/]*)\/)?([^\/]*)/)
  if (nm && (nm[1] || nm[2])) {
    if (nm[1] && nm[2]) return '@' + nm[1] + '/' + nm[2]
    return nm[2] || (nm[1] ? '@' + nm[1] : 'unknown')
  }
  return guessPkg(s)
}

// True streaming tail: read the file in chunks from the end until we have
// at least maxLines lines, or we hit the start of the file. Handles large
// log files (multi-hundred-MB) without slurping the whole thing into memory.
// Returns the lines oldest-first, capped at maxLines.
function tailFileByLines(file, maxLines) {
  const cap = Math.max(1, maxLines | 0)
  let fd
  try { fd = fs.openSync(file, 'r') } catch (_) { return [] }
  try {
    const stat = fs.fstatSync(fd)
    const size = stat.size
    if (size === 0) return []
    // Read in 64 KiB chunks from the end. Keep accumulating until we
    // have seen more than cap newlines OR we reach the start of the file.
    const CHUNK = 64 * 1024
    const buf = Buffer.alloc(CHUNK)
    let pos = size
    let pending = ''
    let lines = []
    let stop = false
    while (pos > 0 && !stop) {
      const want = Math.min(CHUNK, pos)
      pos -= want
      const n = fs.readSync(fd, buf, 0, want, pos)
      if (n <= 0) break
      const chunk = buf.slice(0, n).toString('utf8') + pending
      // Split on \n; last element is either '' (clean boundary) or the
      // partial first line of this chunk that we'll prepend on next iter.
      const parts = chunk.split('\n')
      pending = parts.shift() // the incomplete leading line
      for (let i = parts.length - 1; i >= 0; i--) {
        const line = parts[i]
        if (line.length === 0) continue
        lines.unshift(line)
        if (lines.length > cap) { lines.shift(); stop = true; break }
      }
    }
    if (!stop && pending && pending.length > 0) {
      lines.unshift(pending)
      while (lines.length > cap) lines.shift()
    }
    return lines
  } catch (_) { return [] }
  finally { try { fs.closeSync(fd) } catch (_) {} }
}

function triage(buf) {
  const joined = buf.join('\n')
  const sorted = [...PATTERNS].sort((a, b) => b.pri - a.pri)
  for (const p of sorted) {
    const m = joined.match(p.re)
    if (m) return Object.assign({ matched: p.id }, p.act(m))
  }
  return { matched: null, kind: 'safe-mode', reason: 'no-pattern-matched' }
}

// ---------- health probe ------------------------------------------------------

/**
 * One HTTP GET against a path on dsh web. Resolves true ONLY on a 200.
 * Shared by probe() so / and /health use identical timeout + error
 * handling.
 */
function probePath(p) {
  return new Promise((resolve) => {
    let done = false
    const settle = (v) => { if (!done) { done = true; resolve(v) } }
    const req = http.request({
      host: '127.0.0.1',
      port: WEB_PORT,
      path: p,
      method: 'GET',
      timeout: 2000,
    }, (res) => {
      // Drain the body then settle on the status. Do NOT resolve before
      // draining or the socket can hang open across ticks.
      const code = res.statusCode
      res.resume()
      res.once('end', () => settle(code === 200))
      // Belt-and-braces: if the server keeps the connection open without
      // sending an end, the request timeout below will destroy us so we
      // never hang a tick.
    })
    req.on('timeout', () => { req.destroy(); settle(false) })
    req.on('error',   () => settle(false))
    req.end()
  })
}

/**
 * Is dsh web healthy? Healthy = EITHER the GUI shell at / answers 200
 * OR a semantic /health route answers 200.
 *
 * Why two: dsh web historically exposed no /health route, so probing
 * /health alone (the pre-v0.2.27 behavior) 404'd on a perfectly healthy
 * GUI — the watchdog concluded "alive but broken", triaged an empty
 * log, and downgrade-stormed into safe-mode on every incident. The /
 * probe catches the GUI actually being served; the /health probe stays
 * for forward-compat in case a future dsh adds a real health endpoint.
 */
function probe() {
  // Health is the OR of two independent probes: the GUI shell (/) and a
  // semantic /health route (forward-compat; 404 on current dsh but will
  // 200 if a future dsh adds one). Promise.all gives us BOTH answers in
  // one round-trip latency (the two requests run concurrently), and a
  // single 200 on either is enough to call the server healthy.
  return Promise.all([
    probePath('/').catch(() => false),
    probePath('/health').catch(() => false),
  ]).then(([root, health]) => root || health)
}

// ---------- process control ---------------------------------------------------

function pidAlive(pid) {
  if (!Number.isInteger(pid) || pid <= 0) return false
  try { process.kill(pid, 0); return true }
  catch (e) { return e.code === 'EPERM' }
}

function readWebPid() {
  try {
    const n = Number(fs.readFileSync(WEB_PID, 'utf8').trim())
    return Number.isInteger(n) && n > 0 ? n : null
  } catch (_) { return null }
}

function portHasListener(port) {
  // Try to open a TCP connection to 127.0.0.1:port. If the OS refuses
  // (ECONNREFUSED) nothing is listening. A successful connect means a
  // listener is present, regardless of whether it answers HTTP correctly.
  return new Promise((resolve) => {
    const sock = net.createConnection({ host: '127.0.0.1', port: port, timeout: 1500 })
    let settled = false
    const finish = (v) => { if (!settled) { settled = true; try { sock.destroy() } catch (_) {}; resolve(v) } }
    sock.once('connect', () => finish(true))
    sock.once('error',   () => finish(false))
    sock.once('timeout', () => finish(false))
  })
}

/**
 * Ask the platform service to relaunch dsh web.
 *
 * Design intent: the watchdog does NOT replace the platform service
 * that owns dsh web's lifecycle. macOS launchd, Linux systemd, and
 * Windows Task Scheduler all restart dsh web on crash; the doctor
 * merely nudges them when the doctor notices dsh web is gone and the
 * platform service has not (yet) acted.
 *
 * - macOS: launchctl kickstart -k gui/<uid>/<label> restarts the
 *   service. The label is read from the platform plist that the
 *   install step wrote next to the watchdog script.
 * - Linux: systemctl --user restart <unit> restarts the user unit.
 * - Windows: Task Scheduler can be triggered via schtasks /Run.
 *
 * Returns true if a relaunch was successfully issued, false if no
 * platform service is registered (in which case the caller falls back
 * to a direct startWeb() spawn).
 */
function relaunchViaPlatform() {
  const label = readPlatformLabel()
  if (!label) {
    log('INFO', 'no platform label recorded; cannot kickstart')
    return false
  }
  if (process.platform === 'darwin') {
    const uid = process.getuid ? process.getuid() : 501
    const target = 'gui/' + uid + '/' + label
    try {
      cp.execFileSync('launchctl', ['kickstart', '-k', target], { stdio: 'pipe' })
      log('INFO', 'launchctl kickstart -k ' + target + ' issued')
      return true
    } catch (e) {
      log('WARN', 'launchctl kickstart failed: ' + (e.stderr ? e.stderr.toString() : e.message))
      return false
    }
  }
  if (process.platform === 'linux') {
    try {
      cp.execFileSync('systemctl', ['--user', 'restart', label], { stdio: 'pipe' })
      log('INFO', 'systemctl --user restart ' + label + ' issued')
      return true
    } catch (e) {
      log('WARN', 'systemctl restart failed: ' + (e.stderr ? e.stderr.toString() : e.message))
      return false
    }
  }
  if (process.platform === 'win32') {
    try {
      cp.execFileSync('schtasks', ['/Run', '/TN', label], { stdio: 'pipe' })
      log('INFO', 'schtasks /Run /TN ' + label + ' issued')
      return true
    } catch (e) {
      log('WARN', 'schtasks failed: ' + (e.stderr ? e.stderr.toString() : e.message))
      return false
    }
  }
  return false
}

function readPlatformLabel() {
  // The install step writes the dsh web service label to
  // $DSH_HOME/doctor/.doctor-web-label so the watchdog can find it
  // without enumerating the platform's service registry.
  const f = path.join(DOCTOR_DIR, '.doctor-web-label')
  try { return fs.readFileSync(f, 'utf8').trim() || null }
  catch (_) { return null }
}

function killWeb() {
  const pid = readWebPid()
  if (!pid) { log('WARN', 'no recorded web pid; skipping kill'); return false }
  if (!pidAlive(pid)) { log('INFO', 'recorded web pid ' + pid + ' already dead'); return true }
  try { process.kill(pid, 'SIGTERM'); log('INFO', 'SIGTERM → ' + pid); return true }
  catch (e) { log('WARN', 'kill failed: ' + e.message); return false }
}

function startWeb() {
  const dsh = process.env.DSH_BIN || 'dsh'
  const args = ['web', '--port', String(WEB_PORT)]
  if (process.env.DSH_NO_OPEN === '1' || process.env.DSH_NO_OPEN === 'true') args.push('--no-open')
  try {
    const child = cp.spawn(dsh, args, {
      detached: true,
      stdio: ['ignore', fs.openSync(path.join(DOCTOR_DIR, 'logs', 'dsh-web.log'), 'a'), fs.openSync(path.join(DOCTOR_DIR, 'logs', 'dsh-web.log'), 'a')],
      env: Object.assign({}, process.env, { DSH_HOME: DSH_HOME }),
      cwd: DSH_HOME,
    })
    child.unref()
    log('INFO', 'spawned dsh web pid=' + child.pid)
    return child.pid
  } catch (e) {
    log('ERROR', 'spawn failed: ' + e.message)
    return null
  }
}

// ---------- patch manipulation ------------------------------------------------

/**
 * Stage a user-visible error so the next probe (or the next dsh web
 * boot) can surface it. We do not have a real notification channel
 * from the watchdog, so we drop a marker file the user can find, and
 * log loudly. dsh-doctor's dsh_doctor_status tool also picks this
 * up (in-process).
 */
function notifyUser(reason) {
  const f = path.join(DOCTOR_DIR, '.doctor-user-action-required')
  const stamp = new Date().toISOString() + ' ' + reason + '\n'
  try { fs.appendFileSync(f, stamp, { mode: 0o600 }) } catch (_) {}
  log('ERROR', 'human action required: ' + reason)
  log('ERROR', 'see ' + f + ' (read-only)')
}

/**
 * Move a corrupt cordis.patch.yml aside so dsh web can boot with an
 * empty patch (just dsh-core bundles). The user can re-add their
 * custom rows by hand once dsh web is back up.
 */
function cleanupCorruptPatch() {
  try {
    if (!fs.existsSync(PATCH_F)) return
    const backup = PATCH_F + '.doctor-broken-' + Date.now()
    fs.renameSync(PATCH_F, backup)
    log('WARN', 'corrupt patch moved to ' + backup)
  } catch (e) {
    log('WARN', 'could not move corrupt patch: ' + e.message)
  }
}

/**
 * True disable: find the row whose id: equals pluginId in the
 * profile's cordis.patch.yml, move it out of the patch (into a sibling
 * .doctor-disabled-<id> file so the user can restore it by hand), and
 * atomically rewrite the patch without that row.
 *
 * Until v0.2.22 the "simple path" only WROTE the sibling marker file
 * and never touched cordis.patch.yml — so on restart the broken row was
 * still mounted, the boot tripped over it again, and the recovery
 * eventually escalated to safe-mode. The marker existed but nothing
 * consumed it; this function makes the simple path actually disable.
 */
/**
 * Remove the patch row whose id: equals rowId. A row is one "- id:" line
 * plus its indented continuation lines (name/config/...). Everything that
 * does not belong to the matched row is preserved in order. The row is
 * found by a line-anchored id: match, which matches how the doctor's
 * own bundle rows are written.
 */
function removeRowFromPatch(lines, rowId) {
  const out = []
  let pending = []         // lines of the current row, not yet classified
  let pendingIsMatch = false
  let inRowList = false    // inside an insert: block
  const flush = function () {
    if (pending.length === 0) return
    if (!pendingIsMatch) for (let i = 0; i < pending.length; i++) out.push(pending[i])
    pending = []
    pendingIsMatch = false
  }
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    // NOTE: the tag is String.raw (no escape cooking), so backslash
    // escapes in these regexes reach the generated script as written —
    // the same convention as the PATTERNS table above.
    if (/^-\s+insert\s*:/.test(line)) {
      flush()
      inRowList = true
      out.push(line)
      continue
    }
    if (!inRowList) {
      // Top-level line outside any insert: block — always preserved.
      flush()
      inRowList = false
      out.push(line)
      continue
    }
    if (/^\s+-\s+id\s*:/.test(line)) {
      const m = line.match(/^\s+-\s+id\s*:\s*['"]?([^'"'\s]+)['"]?/)
      flush()
      pending = [line]
      pendingIsMatch = !!(m && m[1] && String(m[1]) === String(rowId))
      continue
    }
    // Continuation of the current row (or a blank line between rows).
    pending.push(line)
    continue
  }
  flush()
  return out
}

function stageDisableRow(pluginId) {
  if (!pluginId) return false
  const safe = String(pluginId).replace(/[^A-Za-z0-9_.\-@/]/g, '_')
  const target = PATCH_F + '.doctor-disabled-' + safe
  try {
    const raw = fs.readFileSync(PATCH_F, 'utf8')
    const lines = raw.split(/\r?\n/)
    const pruned = removeRowFromPatch(lines, pluginId)
    if (pruned.length === lines.length) {
      // Row not found in the patch (it may come from a bundle manifest
      // instead of the user patch). Keep the legacy marker file so a
      // human can trace what the doctor thought was broken.
      const body = '# dsh-doctor auto-disabled (row not found in cordis.patch.yml): ' + pluginId + '\n# Generated ' + new Date().toISOString() + '\n# Remove this file once the plugin is fixed.\n'
      fs.writeFileSync(target, body, { mode: 0o600 })
      log('WARN', 'disable row ' + pluginId + ' not found in ' + PATCH_F + ' — wrote marker only')
      return true
    }
    // Backup the original, write the pruned patch, record the disabled row.
    const backup = PATCH_F + '.doctor-bak-' + Date.now()
    fs.copyFileSync(PATCH_F, backup)
    const body = '# dsh-doctor auto-disabled: ' + pluginId + '\n# Generated ' + new Date().toISOString() + '\n# Original patch backed up at ' + backup + '\n# To re-enable, restore that backup (or re-add the row to ' + PATCH_F + ').\n'
    fs.writeFileSync(target, body, { mode: 0o600 })
    const tmp = PATCH_F + '.doctor-disable.tmp'
    fs.writeFileSync(tmp, pruned.join('\n') + (pruned.length ? '\n' : ''), { mode: 0o600 })
    fs.renameSync(tmp, PATCH_F)
    log('INFO', 'disabled row ' + pluginId + ' from ' + PATCH_F + ' (backup ' + backup + ', record ' + target + ')')
    return true
  } catch (e) {
    log('ERROR', 'stage disable failed: ' + e.message)
    return false
  }
}

function activateSafeMode(allowList) {
  const header = [
    '# dsh-doctor safe-mode patch (auto-generated).',
    '# Activated at ' + new Date().toISOString() + ' by the watchdog.',
    '# Remove this file (or rename to .disabled) to exit safe mode.',
  ].join('\n')
  const rows = allowList.map(function (id) { return '    - id: ' + id + '\n      name: ' + id + '\n      config: {safeMode: true}' })
  // Empty-allow-list sentinel: id AND name must be the sentinel, never
  // the bare word dsh-doctor — cordis resolves the name to the running
  // plugin row, so the old name dsh-doctor silently disabled THIS
  // plugin while safe mode was active (the v0.2.20 bug, which this
  // copy of the generator re-introduced). buildSafeModePatch in
  // src/safe-mode.ts is the reference; a test pins the two
  // byte-for-byte on the rows. (No backticks in this comment: the
  // whole file is a raw template — a backtick ends the string.)
  const body = header + '\n- insert:\n' + (rows.length ? rows.join('\n') + '\n' : '    - id: dsh-doctor-safe-mode-sentinel\n      name: dsh-doctor-safe-mode-sentinel\n      config: {safeModeSentinel: true}\n')
  try { fs.writeFileSync(SAFE_MODE, body, { mode: 0o600 }); log('INFO', 'safe-mode patch written: ' + SAFE_MODE) }
  catch (e) { log('ERROR', 'safe-mode write failed: ' + e.message) }
}

function clearSafeMode() {
  try { fs.unlinkSync(SAFE_MODE); log('INFO', 'safe-mode patch cleared') }
  catch (e) { if (e.code !== 'ENOENT') log('WARN', 'safe-mode clear failed: ' + e.message) }
}

// ---------- main loop ---------------------------------------------------------

let consecutiveFailures = 0
let firstFailureAt = 0
let recoveryAttempts = 0
let lastRecoveryAt = 0
let installedAt = Date.now()
let tickCount = 0
// Emit one heartbeat line every N ticks so a healthy watchdog is
// visibly alive in the log. Heartbeat failures are not errors.
const HEARTBEAT_EVERY_N_TICKS = 10

async function tick() {
  // Hard exit if we were uninstalled.
  try { fs.statSync(INSTALLED) }
  catch (_) { log('INFO', 'installed marker missing — exiting'); cleanup(); process.exit(0) }

  loadConfig()

  // Stamp the last-tick marker so the status tool can tell the user
  // "the watchdog has been alive for N seconds" — much friendlier than
  // "unknown uptime". Best-effort write; never throw out of tick().
  try { fs.writeFileSync(LAST_TICK, String(Date.now())) } catch (_) {}
  tickCount++
  const healthy = await probe()
  if (healthy) {
    if (consecutiveFailures > 0 && firstFailureAt > 0) {
      log('INFO', 'health probe OK — recovered after ' + ((Date.now() - firstFailureAt) / 1000).toFixed(1) + 's')
      // If we entered safe mode, we are now stable; keep safe mode until the
      // user explicitly exits it. The plugin's tool dsh_doctor_safe_mode_exit
      // is the supported way to do that.
    }
    consecutiveFailures = 0
    firstFailureAt = 0
    if (tickCount % HEARTBEAT_EVERY_N_TICKS === 0) {
      const uptimeSec = Math.round((Date.now() - installedAt) / 1000)
      log('INFO', 'health probe OK (heartbeat) uptime=' + uptimeSec + 's ticks=' + tickCount)
    }
    return
  }

  consecutiveFailures += 1

  // Diagnose the kind of failure. The platform service (LaunchAgent /
  // systemd / Task Scheduler) owns dsh web's lifecycle — the doctor
  // does NOT touch it. The doctor observes and reacts within ONE
  // probe cycle (default 2s, not 30s+90s of previous designs).
  //
  // The user-facing latency budget is tight: dsh web serves a GUI,
  // a human is staring at a stalled or empty screen. We want triage
  // to fire on the very first sign of trouble.
  const hasPort = await portHasListener(WEB_PORT)

  if (!hasPort) {
    if (consecutiveFailures === 1) {
      // First failure with empty port. Give the platform service
      // ONE fast window (the next probe, 2s away) to recover on
      // its own. If it does, we'll see the port listening again
      // and skip triage entirely.
      log('WARN', 'health probe failed, port ' + WEB_PORT + ' empty — giving platform service 1 probe to recover')
      return
    }
    // 2nd consecutive failure with empty port: platform service
    // cannot recover dsh web. Triage now.
    log('WARN', 'platform service failed to recover dsh web after ' + consecutiveFailures + ' probes — entering crash-loop triage')
    if (firstFailureAt === 0) firstFailureAt = Date.now()
    const elapsed = Date.now() - firstFailureAt
    if (recoveryAttempts >= 3 && (Date.now() - lastRecoveryAt) < 5 * 60 * 1000) {
      log('WARN', 'recovery rate-limited — will retry next tick')
      return
    }
    return triageAndDisable(elapsed)
  }

  // Port has a listener but health probe is failing → dsh web is
  // alive but broken. 1 failure is enough — the user is staring at
  // a stalled GUI; we don't make them wait 90s for a 3-failure
  // threshold.
  if (consecutiveFailures === 1) {
    log('WARN', 'first probe failure with port listening — dsh web alive but broken; reading log for triage')
  }
  if (firstFailureAt === 0) firstFailureAt = Date.now()
  const elapsed2 = Date.now() - firstFailureAt
  if (recoveryAttempts >= 3 && (Date.now() - lastRecoveryAt) < 5 * 60 * 1000) {
    log('WARN', 'recovery rate-limited — will retry next tick')
    return
  }
  log('WARN', 'triaging dsh web failure now (no ' + CFG.healthFailuresToRecover + '-failure wait — user latency budget)')
  return triageAndDisable(elapsed2)
}

/**
 * Read dsh web's log, identify the broken plugin (if any), and write
 * a disable row for it. The platform service will then restart dsh
 * web with the broken plugin disabled.
 */
function triageAndDisable(elapsed) {
  const webLog = path.join(DOCTOR_DIR, 'logs', 'dsh-web.log')
  // Streaming tail — see tailFileByLines above. Honours CFG.triageLogLines
  // so operators can widen / narrow the window without editing code.
  const want = Math.max(50, Math.min(50000, CFG.triageLogLines | 0))
  const lines = tailFileByLines(webLog, want)
  const plan = triage(lines)
  log('INFO', 'triage: matched=' + plan.matched + ' kind=' + plan.kind + (plan.id ? ' id=' + plan.id : ''))

  if (elapsed > CFG.recoveryBudgetMs) {
    log('WARN', 'recovery budget exhausted (' + elapsed + 'ms > ' + CFG.recoveryBudgetMs + 'ms) — staging safe-mode')
    activateSafeMode(CFG.safeModeBundles)
    recoveryAttempts += 1
    lastRecoveryAt = Date.now()
    return
  }

  if (plan.kind === 'kill-pid-and-restart') {
    // A port conflict: an orphan pid is holding the listener so a
    // fresh web process cannot bind. Killing the recorded pid is the
    // exact fix — the platform service then re-pulls dsh web with
    // nothing to conflict against. Disabling a row (or safe-mode)
    // here would demote a working plugin for no reason.
    const killed = killWeb()
    if (!killed) {
      // No recorded pid / kill failed: fall through to safe-mode so
      // at least something changes and the platform service retries.
      log('WARN', 'kill-pid-and-restart: kill failed; falling back to safe-mode')
      activateSafeMode(CFG.safeModeBundles)
    } else {
      log('INFO', 'kill-pid-and-restart: orphan pid killed; waiting for platform service to restart dsh web')
    }
  } else if (plan.kind === 'notify-user') {
    // The doctor cannot fix this; the human must. Log loudly so it
    // surfaces in dsh_doctor_diagnose and any operator tailing
    // the log file.
    log('ERROR', 'UNRECOVERABLE — human action required: ' + plan.reason)
    notifyUser(plan.reason)
  } else if (plan.kind === 'cleanup-and-restart') {
    log('WARN', 'cleanup action: ' + plan.reason)
    cleanupCorruptPatch()
    log('INFO', 'corrupt patch moved aside; waiting for platform service to restart dsh web')
  } else if (plan.kind === 'safe-mode') {
    activateSafeMode(CFG.safeModeBundles)
  } else if (plan.kind === 'disable-row' && plan.id) {
    stageDisableRow(plan.id)
  } else {
    // Nothing specific to disable — fall back to safe-mode.
    log('WARN', 'no specific plugin identified; activating safe-mode')
    activateSafeMode(CFG.safeModeBundles)
  }

  recoveryAttempts += 1
  lastRecoveryAt = Date.now()
  // Reset failure tracking so we wait for the next launchd pull
  // to actually run with the disabled plugin.
  consecutiveFailures = 0
  firstFailureAt = 0
  log('INFO', 'triage action staged; waiting for platform service to restart dsh web')
}

function loop() {
  // Use a per-tick setTimeout inside finally so a rejected or thrown tick
  // can never break the loop. Previous setTimeout-after-then chain silently
  // died if tick() returned a never-resolving promise (observed live:
  // 5 minutes of 0% CPU on PID 71994 after a healthy dsh web restart).
  // finally guarantees the next tick is always scheduled, even when
  // tick() throws synchronously. The arrow functions are written
  // without TypeScript annotations on purpose: WATCHDOG_STANDALONE_BODY
  // is a tagged-template string that tsc parses byte by byte, so any
  // return-type annotation like '() => void' would leak into the
  // generated script and break the runtime parse.
  const run = () => {
    tick()
      .catch((e) => log('ERROR', 'tick: ' + (e && e.message ? e.message : String(e))))
      .finally(() => setTimeout(run, CFG.healthIntervalMs))
  }
  run()
}

function cleanup() {
  try { fs.unlinkSync(PID_F) } catch (_) {}
  try { fs.unlinkSync(LAST_TICK) } catch (_) {}
  try { fs.unlinkSync(STARTED) } catch (_) {}
}

function singleInstance() {
  try {
    const old = Number(fs.readFileSync(PID_F, 'utf8').trim())
    if (Number.isInteger(old) && old > 0 && pidAlive(old)) {
      log('WARN', 'another watchdog already running pid=' + old + ' — exiting')
      process.exit(0)
    }
  } catch (_) {}
  fs.writeFileSync(PID_F, String(process.pid), { mode: 0o600 })
  // Stamp the start-time marker so the plugin's status tool can report
  // a real uptime. Written ONCE per process lifetime (before the first
  // tick), removed by cleanup() on clean shutdown or uninstall.
  try { fs.writeFileSync(STARTED, String(Date.now()), { mode: 0o600 }) } catch (_) {}
  // Update the in-memory installedAt that the heartbeat log uses.
  installedAt = Date.now()
}

function handleSignal(sig) {
  log('INFO', 'received ' + sig + ' — exiting')
  cleanup()
  process.exit(0)
}

process.on('SIGINT',  () => handleSignal('SIGINT'))
process.on('SIGTERM', () => handleSignal('SIGTERM'))
process.on('SIGHUP',  () => { log('INFO', 'SIGHUP — reloading config'); loadConfig() })

log('INFO', 'watchdog started pid=' + process.pid + ' home=' + DSH_HOME + ' port=' + WEB_PORT)
singleInstance()
loop()
`
