// @ts-nocheck — the WATCHDOG_STANDALONE_BODY string below is raw
// JavaScript that we hand to `new Function()` at install time. TypeScript
// would otherwise parse every character and reject arrow functions with
// return-type annotations like `() => void` that are perfectly valid JS.
// Keep this file pure-JS-shaped (no TS-only syntax inside the template).
/* eslint-disable */
/**
 * Source-of-truth body for the standalone watchdog script.
 *
 * This module exports a string of valid JavaScript that:
 *   - depends only on Node built-ins (no `node_modules` access),
 *   - runs as the main module of a fresh `node` invocation,
 *   - implements the full state machine in docs/ARCHITECTURE.md.
 *
 * The plugin reads this string, prepends a header (version stamp + safety
 * disclaimer), and writes it to `$DSH_HOME/doctor/watchdog.js` at install
 * time. Upgrading the plugin regenerates the script — the *next* watchdog
 * tick picks up the new body. No re-spawn dance.
 *
 * @module dsh-doctor/watchdog.standalone
 */

// We use `String(...)` instead of `String.raw` so TypeScript does not
// type-check the template literal as a `TemplateStringsArray` (which
// would reject JS like `(): void => ...`). `String` accepts `any` so
// anything inside the backticks is treated as opaque data.
export const WATCHDOG_STANDALONE_BODY: string = String`'use strict'
/**
 * dsh-doctor watchdog — standalone, dependency-free, runs as a per-user
 * platform service. This file is generated by the @d86e/dsh-doctor plugin
 * at install time and regenerated on upgrade. Do not edit by hand; edit
 * src/watchdog.standalone.ts and run dsh_doctor_reinstall.
 *
 * The script is intentionally simple: a single async loop, one health
 * probe per tick, three possible recovery paths (simple / complex / alarm).
 * The 60-second recovery budget is enforced by a monotonic timer.
 */

const fs   = require('node:fs')
const path = require('node:path')
const os   = require('node:os')
const http = require('node:http')
const cp   = require('node:child_process')
const crypto = require('node:crypto')

// ---------- paths & config ----------------------------------------------------

const DSH_HOME   = process.env.DSH_HOME   || path.join(os.homedir(), '.dsh')
const WEB_PORT   = Number(process.env.DSH_WEB_PORT) || 3080
const DOCTOR_DIR = path.join(DSH_HOME, 'doctor')
const CONFIG_F   = path.join(DOCTOR_DIR, 'config.json')
const LOG_F      = path.join(DOCTOR_DIR, 'logs', 'watchdog.log')
const LKG_F      = path.join(DOCTOR_DIR, 'last-known-good.json')
const INSTALLED  = path.join(DOCTOR_DIR, '.doctor-installed')
const STOPPED    = path.join(DOCTOR_DIR, '.doctor-stopped')
const LOCK       = path.join(DOCTOR_DIR, '.doctor-restart.lock')
const PID_F      = path.join(DOCTOR_DIR, '.doctor-watchdog.pid')
const SAFE_MODE  = path.join(DOCTOR_DIR, 'safe-mode.patch.yml')
const PROFILE_DIR= path.join(DSH_HOME, 'profiles', 'web')
const PATCH_F    = path.join(PROFILE_DIR, 'cordis.patch.yml')
const WEB_PID    = path.join(PROFILE_DIR, '.dsh-web.pid')
const LOG_MAX    = 5 * 1024 * 1024
const LOG_BACKUPS= 3

let CFG = {
  healthIntervalMs: 30000,
  healthFailuresToRecover: 3,
  recoveryBudgetMs: 60000,
  safeModeBundles: ['dsh-core'],
}

// ---------- logging (rotation) ------------------------------------------------

function log(level, msg) {
  const ts = new Date().toISOString()
  const line = '[' + ts + '] [' + level + '] ' + msg + '\\n'
  try { fs.mkdirSync(path.dirname(LOG_F), { recursive: true }) } catch (_) {}
  try { fs.appendFileSync(LOG_F, line) } catch (_) {}
  try {
    const st = fs.statSync(LOG_F)
    if (st.size >= LOG_MAX) rotate()
  } catch (_) {}
}

function rotate() {
  for (let i = LOG_BACKUPS; i >= 1; i--) {
    const src = i === 1 ? LOG_F : (LOG_F + '.' + (i - 1))
    const dst = LOG_F + '.' + i
    try { fs.renameSync(src, dst) } catch (_) {}
  }
}

// ---------- config load -------------------------------------------------------

function loadConfig() {
  try {
    const txt = fs.readFileSync(CONFIG_F, 'utf8')
    const parsed = JSON.parse(txt)
    if (parsed && typeof parsed === 'object') Object.assign(CFG, parsed)
  } catch (_) {}
  // env overrides
  const n = (k, fb) => {
    const v = process.env[k]
    if (v === undefined || v === '') return fb
    const x = Number(v); return Number.isFinite(x) && x > 0 ? x : fb
  }
  CFG.healthIntervalMs        = n('DSH_DOCTOR_HEALTH_INTERVAL', CFG.healthIntervalMs)
  CFG.healthFailuresToRecover = n('DSH_DOCTOR_HEALTH_FAILURES', CFG.healthFailuresToRecover)
  CFG.recoveryBudgetMs        = n('DSH_DOCTOR_BUDGET_MS', CFG.recoveryBudgetMs)
}

// ---------- triage (inlined, dep-free) ---------------------------------------

const PATTERNS = [
  { id: 'eaddrinuse',             pri: 100, re: /EADDRINUSE.*?(?:127\.0\.0\.1|0\.0\.0\.0|::):(\d+)/,           act: () => ({ kind: 'kill-pid-and-restart' }) },
  { id: 'duplicate-loader-entry', pri: 90,  re: /duplicate loader entry id:\s*([A-Za-z0-9_.\-@/]+)/,             act: (m) => ({ kind: 'disable-row', id: m[1] }) },
  { id: 'schema-parse-error',     pri: 80,  re: /Schema (?:parse|validation) error.*?([@A-Za-z0-9_.\-/]+)/,     act: (m) => ({ kind: 'disable-row', id: m[1] }) },
  { id: 'cannot-find-module',     pri: 70,  re: /Cannot find module ['"]([^'"]+)['"]/,                          act: (m) => ({ kind: 'disable-row', id: guessPkg(m[1]) }) },
  { id: 'plugin-load-error',      pri: 60,  re: /(?:Failed to (?:load|apply)|Error (?:loading|applying)) plugin ['"]?([@A-Za-z0-9_.\-/]+)['"]?/,
                                                                                                                  act: (m) => ({ kind: 'disable-row', id: m[1] }) },
]

function guessPkg(spec) {
  if (!spec) return 'unknown'
  const s = String(spec).replace(/^node:/, '')
  const parts = s.split('/')
  if (s.startsWith('@') && parts.length >= 2) return parts[0] + '/' + parts[1]
  return parts[0]
}

function triage(buf) {
  const joined = buf.join('\\n')
  const sorted = [...PATTERNS].sort((a, b) => b.pri - a.pri)
  for (const p of sorted) {
    const m = joined.match(p.re)
    if (m) return Object.assign({ matched: p.id }, p.act(m))
  }
  return { matched: null, kind: 'safe-mode', reason: 'no-pattern-matched' }
}

// ---------- health probe ------------------------------------------------------

function probe() {
  return new Promise((resolve) => {
    const req = http.request({
      host: '127.0.0.1',
      port: WEB_PORT,
      path: '/health',
      method: 'GET',
      timeout: 2000,
    }, (res) => {
      res.resume()
      resolve(res.statusCode === 200)
    })
    req.on('timeout', () => { req.destroy(); resolve(false) })
    req.on('error',   () => resolve(false))
    req.end()
  })
}

// ---------- process control ---------------------------------------------------

function pidAlive(pid) {
  if (!Number.isInteger(pid) || pid <= 0) return false
  try { process.kill(pid, 0); return true }
  catch (e) { return e.code === 'EPERM' }
}

function readWebPid() {
  try {
    const n = Number(fs.readFileSync(WEB_PID, 'utf8').trim())
    return Number.isInteger(n) && n > 0 ? n : null
  } catch (_) { return null }
}

function killWeb() {
  const pid = readWebPid()
  if (!pid) { log('WARN', 'no recorded web pid; skipping kill'); return false }
  if (!pidAlive(pid)) { log('INFO', 'recorded web pid ' + pid + ' already dead'); return true }
  try { process.kill(pid, 'SIGTERM'); log('INFO', 'SIGTERM → ' + pid); return true }
  catch (e) { log('WARN', 'kill failed: ' + e.message); return false }
}

function startWeb() {
  const dsh = process.env.DSH_BIN || 'dsh'
  const args = ['web', '--port', String(WEB_PORT)]
  if (process.env.DSH_NO_OPEN === '1' || process.env.DSH_NO_OPEN === 'true') args.push('--no-open')
  try {
    const child = cp.spawn(dsh, args, {
      detached: true,
      stdio: ['ignore', fs.openSync(path.join(DOCTOR_DIR, 'logs', 'dsh-web.log'), 'a'), fs.openSync(path.join(DOCTOR_DIR, 'logs', 'dsh-web.log'), 'a')],
      env: Object.assign({}, process.env, { DSH_HOME: DSH_HOME }),
      cwd: DSH_HOME,
    })
    child.unref()
    log('INFO', 'spawned dsh web pid=' + child.pid)
    return child.pid
  } catch (e) {
    log('ERROR', 'spawn failed: ' + e.message)
    return null
  }
}

// ---------- patch manipulation ------------------------------------------------

function stageDisableRow(pluginId) {
  if (!pluginId) return false
  const safe = String(pluginId).replace(/[^A-Za-z0-9_.\-@/]/g, '_')
  const target = PATCH_F + '.doctor-disabled-' + safe
  try {
    const body = '# dsh-doctor auto-disabled: ' + pluginId + '\\n# Generated ' + new Date().toISOString() + '\\n# Remove this file to re-enable the plugin.\\n'
    fs.writeFileSync(target, body, { mode: 0o600 })
    log('INFO', 'staged disable for ' + pluginId + ' at ' + target)
    return true
  } catch (e) {
    log('ERROR', 'stage disable failed: ' + e.message)
    return false
  }
}

function activateSafeMode(allowList) {
  const header = [
    '# dsh-doctor safe-mode patch (auto-generated).',
    '# Activated at ' + new Date().toISOString() + ' by the watchdog.',
    '# Remove this file (or rename to .disabled) to exit safe mode.',
  ].join('\\n')
  const rows = allowList.map(function (id) { return '    - id: ' + id + '\\n      name: ' + id + '\\n      config: {safeMode: true}' })
  const body = header + '\\n- insert:\\n' + (rows.length ? rows.join('\\n') + '\\n' : '    - id: dsh-doctor-safe-mode-sentinel\\n      name: dsh-doctor\\n      config: {safeModeSentinel: true}\\n')
  try { fs.writeFileSync(SAFE_MODE, body, { mode: 0o600 }); log('INFO', 'safe-mode patch written: ' + SAFE_MODE) }
  catch (e) { log('ERROR', 'safe-mode write failed: ' + e.message) }
}

function clearSafeMode() {
  try { fs.unlinkSync(SAFE_MODE); log('INFO', 'safe-mode patch cleared') }
  catch (e) { if (e.code !== 'ENOENT') log('WARN', 'safe-mode clear failed: ' + e.message) }
}

// ---------- main loop ---------------------------------------------------------

let consecutiveFailures = 0
let firstFailureAt = 0
let recoveryAttempts = 0
let lastRecoveryAt = 0
let installedAt = Date.now()
let tickCount = 0
// Emit one heartbeat line every N ticks so a healthy watchdog is
// visibly alive in the log. Heartbeat failures are not errors.
const HEARTBEAT_EVERY_N_TICKS = 10

async function tick() {
  // Hard exit if we were uninstalled.
  try { fs.statSync(INSTALLED) }
  catch (_) { log('INFO', 'installed marker missing — exiting'); cleanup(); process.exit(0) }

  loadConfig()
  tickCount++
  const healthy = await probe()
  if (healthy) {
    if (consecutiveFailures > 0 && firstFailureAt > 0) {
      log('INFO', 'health probe OK — recovered after ' + ((Date.now() - firstFailureAt) / 1000).toFixed(1) + 's')
      // If we entered safe mode, we are now stable; keep safe mode until the
      // user explicitly exits it. The plugin's tool dsh_doctor_safe_mode_exit
      // is the supported way to do that.
    }
    consecutiveFailures = 0
    firstFailureAt = 0
    if (tickCount % HEARTBEAT_EVERY_N_TICKS === 0) {
      const uptimeSec = Math.round((Date.now() - installedAt) / 1000)
      log('INFO', 'health probe OK (heartbeat) uptime=' + uptimeSec + 's ticks=' + tickCount)
    }
    return
  }

  consecutiveFailures += 1
  if (consecutiveFailures < CFG.healthFailuresToRecover) {
    log('WARN', 'health probe failed (' + consecutiveFailures + '/' + CFG.healthFailuresToRecover + ')')
    return
  }

  // Triage time.
  if (firstFailureAt === 0) firstFailureAt = Date.now()
  const elapsed = Date.now() - firstFailureAt

  // Backoff: max 3 attempts per 5 minutes.
  if (recoveryAttempts >= 3 && (Date.now() - lastRecoveryAt) < 5 * 60 * 1000) {
    log('WARN', 'recovery rate-limited — entering alarm state; will retry in 5s')
    return setTimeout(loop, 5000)
  }

  // Read log.
  const webLog = path.join(DOCTOR_DIR, 'logs', 'dsh-web.log')
  let lines = []
  try {
    const txt = fs.readFileSync(webLog, 'utf8')
    lines = txt.split(/\\\\r?\\\\n/).slice(-200)
  } catch (_) {}
  const plan = triage(lines)
  log('INFO', 'triage: matched=' + plan.matched + ' kind=' + plan.kind + (plan.id ? ' id=' + plan.id : ''))

  // Decide simple vs complex.
  let via = 'simple'
  if (plan.kind === 'safe-mode' || (elapsed > CFG.recoveryBudgetMs / 2 && plan.kind === 'disable-row')) {
    via = 'complex'
  }
  if (elapsed > CFG.recoveryBudgetMs) {
    log('WARN', 'recovery budget exhausted (' + elapsed + 'ms > ' + CFG.recoveryBudgetMs + 'ms) — staging safe-mode for next tick')
    activateSafeMode(CFG.safeModeBundles)
    recoveryAttempts += 1
    lastRecoveryAt = Date.now()
    return
  }

  if (via === 'simple') {
    if (plan.kind === 'kill-pid-and-restart') {
      killWeb()
    } else if (plan.kind === 'disable-row') {
      stageDisableRow(plan.id)
    }
  } else {
    activateSafeMode(CFG.safeModeBundles)
  }

  // Take the restart lock so a user-initiated restart doesn't race us.
  try { fs.writeFileSync(LOCK, String(Date.now())) } catch (_) {}

  startWeb()

  recoveryAttempts += 1
  lastRecoveryAt = Date.now()
}

function loop() {
  // Use a per-tick setTimeout inside finally so a rejected or thrown tick
  // can never break the loop. Previous setTimeout-after-then chain silently
  // died if tick() returned a never-resolving promise (observed live:
  // 5 minutes of 0% CPU on PID 71994 after a healthy dsh web restart).
  // finally guarantees the next tick is always scheduled, even when
  // tick() throws synchronously. The arrow functions are written
  // without TypeScript annotations on purpose: WATCHDOG_STANDALONE_BODY
  // is a tagged-template string that tsc parses byte by byte, so any
  // return-type annotation like '() => void' would leak into the
  // generated script and break the runtime parse.
  const run = () => {
    tick()
      .catch((e) => log('ERROR', 'tick: ' + (e && e.message ? e.message : String(e))))
      .finally(() => setTimeout(run, CFG.healthIntervalMs))
  }
  run()
}

function cleanup() {
  try { fs.unlinkSync(PID_F) } catch (_) {}
}

function singleInstance() {
  try {
    const old = Number(fs.readFileSync(PID_F, 'utf8').trim())
    if (Number.isInteger(old) && old > 0 && pidAlive(old)) {
      log('WARN', 'another watchdog already running pid=' + old + ' — exiting')
      process.exit(0)
    }
  } catch (_) {}
  fs.writeFileSync(PID_F, String(process.pid), { mode: 0o600 })
}

function handleSignal(sig) {
  log('INFO', 'received ' + sig + ' — exiting')
  cleanup()
  process.exit(0)
}

process.on('SIGINT',  () => handleSignal('SIGINT'))
process.on('SIGTERM', () => handleSignal('SIGTERM'))
process.on('SIGHUP',  () => { log('INFO', 'SIGHUP — reloading config'); loadConfig() })

log('INFO', 'watchdog started pid=' + process.pid + ' home=' + DSH_HOME + ' port=' + WEB_PORT)
singleInstance()
loop()
`
